spring.application.name=config-server
server.port=8071
spring.cloud.config.server.native.search-locations=classpath:/config
spring.profiles.active=native

management.endpoints.web.exposure.include=*
management.endpoints.health.probes.enabled=true
management.health.readiness-state.enabled=true
management.health.liveness-state.enabled=true
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}